
services:
  # Входная нода №1 (цепочка: узер -> nginx-1 -> nginx-2 -> nginx-3 -> app)
  nginx-1:
    image: nginx:1.25-alpine
    container_name: proxy-nginx-1
    ports:
      - "8081:80"
    environment:
      - NEXT_HOP=nginx-2:80
      - NGINX_ENVSUBST_FILTER=NEXT_HOP
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    volumes:
      - ./config/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
    depends_on:
      - nginx-2

  # Промежуточная нода №2 (можно слать запросы сюда напрямую, тогда цепочка будет короче)
  nginx-2:
    image: nginx:1.25-alpine
    container_name: proxy-nginx-2
    ports:
      - "8082:80"
    environment:
      - NEXT_HOP=nginx-3:80
      - NGINX_ENVSUBST_FILTER=NEXT_HOP
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    volumes:
      - ./config/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
    depends_on:
      - nginx-3

  # Последняя нода №3 перед бэкендом
  nginx-3:
    image: nginx:1.25-alpine
    container_name: proxy-nginx-3
    ports:
      - "8083:80"
    environment:
      # Для переключения на Go-бэкенд замените на: NEXT_HOP=app-go:8080
      - NEXT_HOP=app-python:5000
      - NGINX_ENVSUBST_FILTER=NEXT_HOP
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    volumes:
      - ./config/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
    depends_on:
      - app-python

  # Бэкенд на Python / Flask
  app-python:
    build:
      context: ./app/python
    container_name: backend-python
    expose:
      - "5000"

  # Бэкенд на Go (параллельный вариант для демонстрации навыков)
  app-go:
    build:
      context: ./app/go
    container_name: backend-go
    expose:
      - "8080"

# Чтобы стенд гарантированно работал на WSL (и на любой другой машине при локальном тесте) - фиксим что что IP шлюза — недоверенный.
# шлюз Docker (твой хост) всегда будет иметь IP 172.16.238.1.
networks:
  default:
    ipam:
      config:
        - subnet: 172.16.238.0/24
        